Repository duckie-team/duckie-android, pull requests merged in 2022-12, with the labels that each got.

#108 GalleryRepository DI 적용 및 코드 정리
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  data/src/main/kotlin/team/duckie/app/android/data/exam/datasource/remote/ExamDataSource.kt
  data/src/main/kotlin/team/duckie/app/android/data/exam/mapper/mapper.kt
  di/src/main/kotlin/team/duckie/app/android/di/datasource/NetworkModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/repository/ExamRepositoryModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/repository/GalleryRepositoryModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/usecase/gallery/GalleryUseCaseModule.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/gallery/usecase/LoadGalleryImagesUseCase.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/CreateProblemScreen.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/empty.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/empty.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/sideeffect/OnboardSideEffect.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/state/OnboardState.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/empty.kt
Labels: 덕질고사

#111 문제 만들기 1단계 UI
  data/src/main/kotlin/team/duckie/app/android/data/exam/datasource/remote/ExamDataSource.kt
  di/src/main/kotlin/team/duckie/app/android/di/datasource/NetworkModule.kt
  feature-ui-create-problem/build.gradle.kts
  feature-ui-create-problem/src/main/AndroidManifest.xml
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/CreateProblemActivity.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/common/FindTagItem.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/common/TextfieldOptions.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/common/TitleAndComponent.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/common/TopAppBar.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/CreateProblemScreen.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/ExamInformationScreen.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/FindExamAreaScreen.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/sideeffect/CreateProblemSideEffect.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/state/CreateProblemState.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/state/CreateProblemStep.kt
  feature-ui-create-problem/src/main/res/values/strings.xml
  presentation/src/main/AndroidManifest.xml
  util-compose/build.gradle.kts
  util-compose/src/main/kotlin/team/duckie/app/android/util/compose/component/DuckieGridLayout.kt
  util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/updateList.kt
Labels: 덕질고사

#114 docs: 프로젝트 문서 정리
  .gitignore
  documents/art/conclusion.svg
  documents/art/one-way-binding.svg
  documents/art/two-way-binding.svg
  documents/internal/README.md
  documents/internal/secrets.md
  documents/tech-stack.md
  secrets.tar.gpg
Labels: bypass, documentation

#115 feat: CI 설정
  .github/workflows/android-ci.yml
  .github/workflows/auto-approve.yml
Labels: bypass, enhancement, github_actions

#123 feat: 온보딩 API 추가
  data/build.gradle.kts
  data/src/main/kotlin/team/duckie/app/android/data/_exception/model/ExceptionBody.kt
  data/src/main/kotlin/team/duckie/app/android/data/_exception/util/responseCatching.kt
  data/src/main/kotlin/team/duckie/app/android/data/_util/JsonBody.kt
  data/src/main/kotlin/team/duckie/app/android/data/_util/JsonBuilder.kt
  data/src/main/kotlin/team/duckie/app/android/data/_util/date.kt
  data/src/main/kotlin/team/duckie/app/android/data/_util/json.kt
  data/src/main/kotlin/team/duckie/app/android/data/auth/mapper/data2domain.kt
  data/src/main/kotlin/team/duckie/app/android/data/auth/model/AccessTokenCheckResponseData.kt
  data/src/main/kotlin/team/duckie/app/android/data/auth/model/AuthJoinResponseData.kt
  data/src/main/kotlin/team/duckie/app/android/data/auth/repository/AuthRepositoryImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/device/repository/DeviceRepositoryImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/file/repository/FileRepositoryImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/gallery/repository/GalleryRepositoryImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/tag/repository/TagRepositoryImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/terms/mapper/data2domain.kt
  data/src/main/kotlin/team/duckie/app/android/data/terms/model/TermsResponseData.kt
  data/src/main/kotlin/team/duckie/app/android/data/terms/repository/TermsRepositoryImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/user/mapper/data2domain.kt
  data/src/main/kotlin/team/duckie/app/android/data/user/model/UserResponse.kt
  data/src/main/kotlin/team/duckie/app/android/data/user/repository/UserRepositoryImpl.kt
  data/src/test/kotlin/team/duckie/app/android/data/util/MockEngine.kt
  data/src/test/kotlin/team/duckie/app/android/data/util/date.kt
  data/src/test/kotlin/team/duckie/app/android/data/util_test/DateTest.kt
  data/src/test/kotlin/team/duckie/app/android/data/util_test/ExceptionTest.kt
  data/src/test/kotlin/team/duckie/app/android/data/util_test/JsonBuilderTest.kt
  data/src/test/kotlin/team/duckie/app/android/data/util_test/JsonMappingTest.kt
  detekt-config.yml
  di/src/main/kotlin/team/duckie/app/android/di/datasource/NetworkModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/repository/BindsModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/repository/ProvidesModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/usecase/auth/AuthUseCaseModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/usecase/device/DeviceUseCaseModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/usecase/file/FileUseCaseModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/usecase/kakao/KakaoUseCaseModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/usecase/tag/TagUseCaseModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/usecase/terms/TermsUseCase.kt
  di/src/main/kotlin/team/duckie/app/android/di/usecase/user/UserUseCaseModule.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/auth/model/AccessTokenCheckResponse.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/auth/model/JoinResponse.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/auth/repository/AuthRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/auth/usecase/CheckAccessTokenUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/auth/usecase/JoinUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/device/repository/DeviceRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/device/usecase/DeviceRegisterUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/file/constant/FileType.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/file/repository/FileRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/file/usecase/FileUploadUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/tag/repository/TagRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/tag/usecase/TagCreateUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/terms/model/Terms.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/terms/repository/TermsRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/terms/usecase/GetTermsUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/user/model/User.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/user/repository/UserRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/user/usecase/UserUpdateUseCase.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
  util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/exception.kt
Labels: enhancement, test
