Repository duckie-team/duckie-android, pull requests merged in 2022-11, with the labels that each got.

#53 앱 설정 구현
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  data/build.gradle.kts
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/datasource/local/LocalSettingDataSource.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/datasource/local/LocalSettingDataSourceImpl.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/datasource/local/room/DuckieDataBase.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/datasource/local/room/SettingDao.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/datasource/remote/RemoteSettingDataSource.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/datasource/remote/RemoteSettingDataSourceImpl.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/mapper/data2domain.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/mapper/domain2data.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/model/AccountInformationData.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/model/SettingData.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/SettingRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/constants/AccountType.kt
  domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/model/AccountInformationEntity.kt
  domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/model/SettingEntity.kt
  domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/repository/SettingRepository.kt
  domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/FetchAccountInformationUseCase.kt
  domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/FetchSettingUseCase.kt
  domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/score/UpdateSettingUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/di/LocalDataSourceModule.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/di/ProvideRepository.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/di/ProvideUseCase.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/di/RemoteDataSourceModule.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/di/RoomModule.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/component/navigation.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/MainActivity.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/home/HomeScreen.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/home/component/modalDrawer.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/navigation/MainNavigation.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/navigation/MainScreens.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/search/SearchScreen.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/component/SettingBase.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/mvi/SettingContract.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/screen/SettingAccountInformationScreen.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/screen/SettingDuckieInformationScreen.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/screen/SettingInquiryScreen.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/screen/SettingMainScreen.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/screen/SettingNotificationScreen.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/screen/SettingPrivacyPolicyScreen.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/screen/SettingScreen.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/screen/SettingTermsScreen.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/utils/SettingStep.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/setting/vm/SettingViewModel.kt
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
  settings.gradle.kts
  shared/android/src/main/kotlin/land/sungbin/androidprojecttemplate/shared/android/base/BaseViewModel.kt
  shared/compose/src/main/kotlin/land/sungbin/androidprojecttemplate/shared/compose/extension/CoroutineScopeContent.kt
Labels: enhancement, dependencies

#54 알림 화면 작업
  build.gradle.kts
  buildSrc/src/main/kotlin/Versions.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/datasource/remote/NotificationDataSource.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/di/RepositoryModule.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/mapper/data2domain.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/mapper/domain2data.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/model/NotificationData.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/NotificationRepositoryImpl.kt
  data/src/main/kotlin/land/sungbin/androidprojecttemplate/data/repository/constants/CollectionNames.kt
  domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/model/NotificationItem.kt
  domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/repository/FetchRepository.kt
  domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/repository/NotificationRepository.kt
  domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/FetchNotificationsUseCase.kt
  domain/src/main/kotlin/land/sungbin/androidprojecttemplate/domain/usecase/fetch/cache/cache.kt
  gradle.properties
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/di/usecase/NotificationUseCaseModule.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/MainActivity.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/navigation/MainNavigation.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/notification/NotificationScreen.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/notification/NotificationState.kt
  presentation/src/main/kotlin/land/sungbin/androidprojecttemplate/ui/main/notification/NotificationViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: enhancement

#57 feat: 구성 파일 업데이트
  .editorconfig
  .gitignore
  CNAME
  LICENSE
  detekt-config.yml
  gradle.properties
  renovate.json
Labels: enhancement

#60 chore: 각각 피쳐별 개별 모듈로 변경
  assets/logo-icon.svg
  build-logic/src/main/kotlin/AndroidApplicationComposePlugin.kt
  build-logic/src/main/kotlin/AndroidApplicationPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposePlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposeUiTestPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryPlugin.kt
  build-logic/src/main/kotlin/DependencyGraphPlugin.kt
  build-logic/src/main/kotlin/JvmDokkaPlugin.kt
  build-logic/src/main/kotlin/JvmJUnit4Plugin.kt
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/ApplicationConstants.kt
  buildSrc/src/main/kotlin/BuildConstants.kt
  buildSrc/src/main/kotlin/ConventionEnum.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/ProjectConstants.kt
  buildSrc/src/main/kotlin/Versions.kt
  buildSrc/src/main/kotlin/extensions.kt
  feature-notification-screen/build.gradle.kts
  feature-notification-screen/src/androidTest/kotlin/team/duckie/app/android/feature/notification/screen/ExampleInstrumentedTest.kt
  feature-notification-screen/src/main/AndroidManifest.xml
  feature-notification-screen/src/test/kotlin/team/duckie/app/android/feature/notification/screen/ExampleUnitTest.kt
  feature-onboard/build.gradle.kts
  feature-onboard/src/androidTest/kotlin/team/duckie/app/android/feature/onboard/ExampleInstrumentedTest.kt
  feature-onboard/src/main/AndroidManifest.xml
  feature-onboard/src/test/kotlin/team/duckie/app/android/feature/onboard/ExampleUnitTest.kt
  feature-setting/build.gradle.kts
  feature-setting/src/androidTest/kotlin/team/duckie/app/android/feature/setting/ExampleInstrumentedTest.kt
  feature-setting/src/main/AndroidManifest.xml
  feature-setting/src/test/kotlin/team/duckie/app/android/feature/setting/ExampleUnitTest.kt
  gradle/common.gradle
  gradle/libs.versions.toml
  gradle/projectDependencyGraph.gradle
  presentation/build.gradle.kts
  settings.gradle.kts
Labels: enhancement

#65 feat: idea 구성 파일 추가
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/copyright/MIT.xml
  .idea/copyright/profiles_settings.xml
  .idea/dictionaries/jisungbin.xml
  .idea/icon.png
  gradle.properties
  settings.gradle.kts
Labels: enhancement

#66 chore: 빌드 캐시 자동 삭제 활성화
  settings.gradle.kts
Labels: gradle

#67 docs: add copyright
  build-logic/build.gradle.kts
  build-logic/gradle.properties
  build-logic/settings.gradle.kts
  build-logic/src/main/kotlin/AndroidApplicationComposePlugin.kt
  build-logic/src/main/kotlin/AndroidApplicationPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposePlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposeUiTestPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryPlugin.kt
  build-logic/src/main/kotlin/DependencyGraphPlugin.kt
  build-logic/src/main/kotlin/JvmDokkaPlugin.kt
  build-logic/src/main/kotlin/JvmJUnit4Plugin.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/ApplicationConstants.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/PluginEnum.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/application.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/compose.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/extensions.kt
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/ConventionEnum.kt
  buildSrc/src/main/kotlin/extensions.kt
  data/build.gradle.kts
  data/src/main/AndroidManifest.xml
  domain/build.gradle.kts
  domain/src/main/AndroidManifest.xml
  feature-ui-notification/build.gradle.kts
  feature-ui-notification/src/main/AndroidManifest.xml
  feature-ui-onboard/build.gradle.kts
  feature-ui-onboard/src/main/AndroidManifest.xml
  feature-ui-setting/build.gradle.kts
  feature-ui-setting/src/main/AndroidManifest.xml
  gradle.properties
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
Labels: documentation

#68 feat: app 모듈 추가
  app/build.gradle.kts
  app/src/androidTest/kotlin/team/duckie/app/android/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/test/kotlin/team/duckie/app/android/ExampleUnitTest.kt
  settings.gradle.kts
Labels: enhancement

#69 feat: app 모듈 구성
  app/build.gradle.kts
  app/src/androidTest/kotlin/team/duckie/app/android/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/team/duckie/app/android/App.kt
  app/src/test/kotlin/team/duckie/app/android/ExampleUnitTest.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement

#71 feat: presentation 모듈 초기 구성
  README.md
  app/src/main/AndroidManifest.xml
  assets/badge/codestyle-duckie.svg
  assets/icon/logo-icon.svg
  assets/icon/playstore.png
  build.gradle.kts
  buildSrc/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/team/duckie/app/android/presentation/MainActivity.kt
  presentation/src/main/res/drawable-hdpi/duckie_onboarding.webp
  presentation/src/main/res/drawable-mdpi/duckie_onboarding.webp
  presentation/src/main/res/drawable-xhdpi/duckie_onboarding.webp
  presentation/src/main/res/drawable-xxhdpi/duckie_onboarding.webp
  presentation/src/main/res/drawable-xxxhdpi/duckie_onboarding.webp
  presentation/src/main/res/drawable/bg_splash.png
  presentation/src/main/res/drawable/duckie_profile.xml
  presentation/src/main/res/drawable/duckie_splash.xml
  presentation/src/main/res/drawable/duckie_splash_logo.webp
  presentation/src/main/res/drawable/ic_launcher_background.xml
  presentation/src/main/res/drawable/kakao_login_large_wide.png
  presentation/src/main/res/drawable/top_bar_logo.xml
  presentation/src/main/res/mipmap-hdpi/ic_launcher.png
  presentation/src/main/res/mipmap-mdpi/ic_launcher.png
  presentation/src/main/res/mipmap-xhdpi/ic_launcher.png
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher.png
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: enhancement

#73 chore: androidHiltPlugin 추가
  app/build.gradle.kts
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/AndroidApplicationPlugin.kt
  build-logic/src/main/kotlin/AndroidHiltPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryPlugin.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/PluginEnum.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/extensions.kt
  buildSrc/src/main/kotlin/ConventionEnum.kt
Labels: gradle

#74 refactor: build-logic 재정비
  build-logic/src/main/kotlin/AndroidApplicationComposePlugin.kt
  build-logic/src/main/kotlin/AndroidApplicationPlugin.kt
  build-logic/src/main/kotlin/AndroidHiltPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposePlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposeUiTestPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryPlugin.kt
  build-logic/src/main/kotlin/DependencyGraphPlugin.kt
  build-logic/src/main/kotlin/JvmDokkaPlugin.kt
  build-logic/src/main/kotlin/JvmJUnit4Plugin.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/PluginEnum.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/application.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/compose.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/extensions.kt
Labels: gradle

#77 feat: StateUpdater 추가
  util-kotlin/build.gradle.kts
  util-viewmodel/build.gradle.kts
  util-viewmodel/src/main/kotlin/team/duckie/app/android/util/viewmodel/BaseViewModel.kt
  util-viewmodel/src/main/kotlin/team/duckie/app/android/util/viewmodel/StateUpdater.kt
  util-viewmodel/src/test/kotlin/team/duckie/app/android/util/viewmodel/BaseViewModelTest.kt
  util-viewmodel/src/test/kotlin/team/duckie/app/android/util/viewmodel/ExampleUnitTest.kt
Labels: enhancement

#81 feat: IntroActivity 구현
  app/src/main/AndroidManifest.xml
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/team/duckie/app/android/presentation/IntroActivity.kt
  presentation/src/main/kotlin/team/duckie/app/android/presentation/MainActivity.kt
  presentation/src/main/res/drawable-hdpi/bg_duckie_intro.webp
  presentation/src/main/res/drawable-mdpi/bg_duckie_intro.webp
  presentation/src/main/res/drawable-xhdpi/bg_duckie_intro.webp
  presentation/src/main/res/drawable-xxhdpi/bg_duckie_intro.webp
  presentation/src/main/res/drawable-xxxhdpi/bg_duckie_intro.webp
  presentation/src/main/res/values/strings.xml
  util-ui/build.gradle.kts
  util-ui/src/main/kotlin/team/duckie/app/android/util/ui/BaseActivity.kt
  util-ui/src/main/kotlin/team/duckie/app/android/util/ui/WindowInsets.kt
  util-ui/src/main/kotlin/team/duckie/app/android/util/ui/activity.kt
Labels: enhancement

#85 documentations
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new_feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  README.md
  assets/art/duckie-launch-options.png
  assets/icon/logo-icon.svg
  assets/project-dependency-graph/graph.dot.png
  build-logic/src/main/kotlin/DependencyGraphPlugin.kt
  documents/codestyle.md
  feature-ui-onboard/build.gradle.kts
Labels: documentation

#89 chore: build-logic 코드 정리
  README.md
  app/build.gradle.kts
  build-logic/build.gradle.kts
  build-logic/gradle.properties
  build-logic/local-convention-enum/PUBLISHING.md
  build-logic/local-convention-enum/build.gradle.kts
  build-logic/local-convention-enum/settings.gradle.kts
  build-logic/local-convention-enum/src/main/kotlin/ConventionEnum.kt
  build-logic/settings.gradle.kts
  build-logic/src/main/kotlin/AndroidHiltPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryComposeUiTestPlugin.kt
  build-logic/src/main/kotlin/DependencyGraphPlugin.kt
  build-logic/src/main/kotlin/JvmJUnit4Plugin.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/PluginEnum.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/application.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/compose.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/extensions.kt
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/ConventionEnum.kt
  feature-ui-onboard/build.gradle.kts
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  settings.gradle.kts
  util-ui/build.gradle.kts
  util-viewmodel/build.gradle.kts
Labels: enhancement, gradle

#96 Fix state bug
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/common/OnboardTopAppBar.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/CategoryScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/TagScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
  presentation/src/main/kotlin/team/duckie/app/android/presentation/screen/IntroScreen.kt
Labels: enhancement

#97 가볍게 코드 정리
  README.md
  Users/jisungbin/AndroidStudioProjects/duckie-app/assets/dependency-graph/project.dot.png
  assets/dependency-graph/project.dot.png
  build-logic/build.gradle.kts
  build-logic/local-convention-enum/settings.gradle.kts
  build-logic/local-enums/PUBLISHING.md
  build-logic/local-enums/build.gradle.kts
  build-logic/local-enums/settings.gradle.kts
  build-logic/local-enums/src/main/kotlin/ConventionEnum.kt
  build-logic/local-enums/src/main/kotlin/PluginEnum.kt
  build-logic/src/main/kotlin/AndroidApplicationPlugin.kt
  build-logic/src/main/kotlin/AndroidHiltPlugin.kt
  build-logic/src/main/kotlin/AndroidLibraryPlugin.kt
  build-logic/src/main/kotlin/DependencyGraphPlugin.kt
  build-logic/src/main/kotlin/JvmLibraryPlugin.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/ApplicationConstants.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/PluginEnum.kt
  build-logic/src/main/kotlin/team/duckie/app/android/convention/application.kt
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/extensions.kt
  di/src/main/kotlin/team/duckie/app/android/di/usecase/gallery/GalleryUseCaseModule.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/ProfileScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/TagScreen.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement

#101 feat: onboard 완성
  app/src/main/AndroidManifest.xml
  assets/dependency-graph/project.dot.png
  data/src/main/kotlin/team/duckie/app/android/data/user/repository/KakaoRepositoryImpl.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/user/model/KakaoUser.kt
  feature-photopicker/build.gradle.kts
  feature-photopicker/src/androidTest/kotlin/team/duckie/app/android/feature/photopicker/ExampleInstrumentedTest.kt
  feature-photopicker/src/main/AndroidManifest.xml
  feature-photopicker/src/main/kotlin/team/duckie/app/android/feature/photopicker/PhotoPicker.kt
  feature-photopicker/src/main/res/values/strings.xml
  feature-photopicker/src/test/kotlin/team/duckie/app/android/feature/photopicker/ExampleUnitTest.kt
  feature-ui-onboard/build.gradle.kts
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/common/OnboardTopAppBar.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/constaint/OnboardStep.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/0_LoginScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/1_ProfileScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/2_CategoryScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/ProfileScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/sideeffect/OnboardSideEffect.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/state/OnboardState.kt
  gradle/libs.versions.toml
  settings.gradle.kts
  util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/FastList.kt
Labels: enhancement
