Repository duckie-team/duckie-android, pull requests merged in 2023-04, with the labels that each got.

#359 Resolve #343
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/DuckieIcon.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/UserFollowingLayout.kt
  shared-ui-compose/src/main/res/drawable/ic_default_profile.xml
Labels: bug

#358 feat: 신고하기 기능 구현
  data/src/main/kotlin/team/duckie/app/android/data/report/datasource/ReportRemoteDataSource.kt
  data/src/main/kotlin/team/duckie/app/android/data/report/datasource/ReportRemoteDataSourceImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/report/repository/ReportRepositoryImpl.kt
  di/src/main/kotlin/team/duckie/app/android/di/datasource/BindsModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/repository/BindsModule.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/report/repository/ReportRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/report/usecase/ReportUseCase.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/DetailViewModel.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/state/DetailState.kt
  feature-ui-detail/src/main/res/drawable/ic_report.xml
  feature-ui-detail/src/main/res/values/strings.xml
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchScreen.kt
  shared-ui-compose/build.gradle.kts
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/Dialog.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/DuckieBottomSheetDialog.kt
  util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/exception/constant.kt
Labels: enhancement

#372 Resolve #361
  data/schemas/team.duckie.app.android.data._local.DuckieDatabase/1.json
  data/src/main/kotlin/team/duckie/app/android/data/_local/Database.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchActivity.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchResultScreen.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/SearchViewModel.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/sideeffect/SearchSideEffect.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/state/SearchState.kt
Labels: bug

#376 feat: 온보딩(시작 가이드) 작업
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/component/BaseBottomLayout.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeActivity.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/guide/GuideStep.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/guide/HomeGuideFeatureScrren.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/guide/HomeGuideScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/guide/viewmodel/HomeGuideSideEffect.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/guide/viewmodel/HomeGuideState.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/guide/viewmodel/HomeGuideViewModel.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/HomeViewModel.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/state/HomeState.kt
  feature-ui-home/src/main/res/drawable/bg_guide_character.png
  feature-ui-home/src/main/res/drawable/bg_guide_create.png
  feature-ui-home/src/main/res/drawable/bg_guide_detail.png
  feature-ui-home/src/main/res/drawable/bg_guide_home.png
  feature-ui-home/src/main/res/values/strings.xml
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/Spacer.kt
  util-compose/src/main/kotlin/team/duckie/app/android/util/compose/constraints.kt
  util-compose/src/main/kotlin/team/duckie/app/android/util/compose/measurable.kt
  util-ui/src/main/kotlin/team/duckie/app/android/util/ui/const/Extras.kt
  util-ui/src/main/kotlin/team/duckie/app/android/util/ui/intent.kt
Labels: enhancement

#379 Resolve #378
  data/src/main/kotlin/team/duckie/app/android/data/_datasource/AuthorizationHeaderClient.kt
  data/src/main/kotlin/team/duckie/app/android/data/user/datasource/UserRemoteDataSourceImpl.kt
Labels: bug

#364 cd 를 통해 배포할 때 versionCode 먼저 올리도록 처리
  .github/workflows/android-cd.yml
Labels: github_actions

#382 feat: Home&Search TODO 해결하기 1차
  data/src/main/kotlin/team/duckie/app/android/data/search/datasource/SearchRemoteDataSourceImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/search/mapper/mapper.kt
  data/src/main/kotlin/team/duckie/app/android/data/search/repository/SearchRepositoryImpl.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/model/SearchType.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/search/model/Search.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/search/repository/SearchRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/search/usecase/GetSearchUseCase.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/viewmodel/CreateProblemViewModel.kt
  feature-ui-exam-result/src/main/java/team/duckie/app/android/feature/ui/exam/result/screen/ExamResultScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/constants/GuideStep.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/DuckieHomeScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeActivity.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/guide/HomeGuideFeatureScrren.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/guide/HomeGuideScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeRecommendFollowingExamScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeRecommendFollowingScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeRecommendScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/ExamSection.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/ExamineeSection.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/RankingScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/search/SearchMainScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/guide/HomeGuideSideEffect.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/guide/HomeGuideState.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/guide/HomeGuideViewModel.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/home/HomeSideEffect.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/home/HomeSkeletonData.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/home/HomeState.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/home/HomeViewModel.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/mapper/mapper.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/ranking/RankingSideEffect.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/ranking/RankingSkeletonData.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/ranking/RankingState.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/ranking/RankingViewModel.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchActivity.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchScreen.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/SearchViewModel.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/sideeffect/SearchSideEffect.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/screen/SettingActivity.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/SolveProblemActivity.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/question/audio/Controller.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/quack/QuackCrossfade.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/quack/QuackNoUnderlineTextField.kt
Labels: enhancement

#384 feat: 팔로우한 유저 중에 덕력고사가 없을 경우 대응
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeRecommendFollowingExamScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeScreen.kt
  feature-ui-home/src/main/res/values/strings.xml
Labels: bug

#395 feat: 마이페이지, 프로필 친구(팔로워/팔로잉)
  app/build.gradle.kts
  data/src/main/kotlin/team/duckie/app/android/data/user/datasource/UserDataSource.kt
  data/src/main/kotlin/team/duckie/app/android/data/user/datasource/UserRemoteDataSourceImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/user/repository/UserRepositoryImpl.kt
  di/src/main/kotlin/team/duckie/app/android/di/usecase/user/UserUseCaseModule.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/user/repository/UserRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/user/usecase/FetchRecommendUserFollowingUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/user/usecase/FetchUserFollowersUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/user/usecase/FetchUserFollowingsUseCase.kt
  feature-ui-friends/src/main/AndroidManifest.xml
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/FriendsActivity.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/FriendsScreen.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/navigator/impl/FriendNavigatorImpl.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/navigator/module/FriendNavigatorModule.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/FriendsSkeletonData.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/FriendsViewModel.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/mapper.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/state/FriendsState.kt
  feature-ui-friends/src/main/res/values/strings.xml
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/DuckieHomeScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeActivity.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/MypageScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/home/HomeSideEffect.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/home/HomeViewModel.kt
  feature-ui-profile/build.gradle.kts
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/ProfileActivity.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/MyProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/OtherProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/ProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/section/ProfileSection.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/ProfileViewModel.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/sideeffect/ProfileSideEffect.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/state/mapper/mapper.kt
  navigator/src/main/kotlin/team/duckie/app/android/navigator/feature/friend/FriendNavigator.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/BackPressedHeadLineTopAppBar.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/EmptyText.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/UserFollowingLayout.kt
  util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/FriendsType.kt
  util-ui/src/main/kotlin/team/duckie/app/android/util/ui/const/Extras.kt
Labels: enhancement

#396 문제 풀기 textfield 스펙 변경
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/answer/shortanswer/EachCharTextField.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/answer/shortanswer/ShortAnswerForm.kt
  feature-ui-solve-problem/src/main/res/values/strings.xml
Labels: enhancement

#394 프로필 수정페이지 구현
  data/src/main/kotlin/team/duckie/app/android/data/user/datasource/UserDataSource.kt
  data/src/main/kotlin/team/duckie/app/android/data/user/datasource/UserRemoteDataSourceImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/user/repository/UserRepositoryImpl.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/user/repository/UserRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/user/usecase/NicknameValidationUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/user/usecase/UserUpdateUseCase.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/component/HeadLineTopAppBar.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/DuckieHomeScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeActivity.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/MypageScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/viewmodel/MyPageViewModel.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/viewmodel/sideeffect/MyPageSideEffect.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
  feature-ui-profile/build.gradle.kts
  feature-ui-profile/src/main/AndroidManifest.xml
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/ProfileActivity.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/component/EditTopAppBar.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/component/GrayBorderButton.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/navigator/impl/ProfileEditNavigatorImpl.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/navigator/module/ProfileNavigatorModule.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/MyProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/edit/ProfileEditActivity.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/edit/ProfileEditScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/ProfileEditViewModel.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/ProfileViewModel.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/intent/MyPageIntent.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/sideeffect/ProfileEditSideEffect.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/sideeffect/ProfileSideEffect.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/state/ProfileEditState.kt
  feature-ui-profile/src/main/res/values/strings.xml
  feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/screen/StartExamScreen.kt
  navigator/src/main/kotlin/team/duckie/app/android/navigator/feature/profile/ProfileEditNavigator.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/LoadingScreen.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/constant/icon.kt
  util-compose/src/main/kotlin/team/duckie/app/android/util/compose/Lifecycle.kt
  util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/debounce.kt
Labels: enhancement

#398 시험 상세 상단 태그 클릭 이벤트 제공, 신고하기 bottomsheet 올라오는 문제 해결
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/ProfileActivity.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/OtherProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/ProfileScreen.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/dialog/DuckieBottomSheetDialog.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/dialog/ReportBottomSheetDialog.kt
Labels: enhancement

#424 refactor: DuckieHome과 Home로직 분리
  feature-ui-home/src/main/AndroidManifest.xml
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/navigator/impl/HomeNavigatorImpl.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainActivity.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeRecommendFollowingExamScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeRecommendFollowingScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeRecommendScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/MypageScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/search/SearchMainScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/MainSideEffect.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/MainState.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/MainViewModel.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/home/HomeSideEffect.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/home/HomeState.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/home/HomeViewModel.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/mypage/MyPageSideEffect.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/mypage/MyPageState.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/mypage/MyPageViewModel.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
  presentation/src/main/kotlin/team/duckie/app/android/presentation/IntroActivity.kt
Labels: enhancement

#426 fix: 온보딩(가이드) 진입 조건 수정
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/OnboardActivity.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/sideeffect/OnboardSideEffect.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/state/OnboardState.kt
Labels: bug

#436 feat: 메인 화면에 신고하기 적용
  feature-ui-home/src/main/AndroidManifest.xml
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainActivity.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeRecommendScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/MainSideEffect.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/MainState.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/MainViewModel.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/dialog/ReportBottomSheetDialog.kt
  util-ui/src/main/kotlin/team/duckie/app/android/util/ui/BaseActivity.kt
Labels: enhancement

#425 feat: friend navigate 기능 구현
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/FriendsActivity.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/FriendsScreen.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/FriendsViewModel.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/sideeffect/FriendsSideEffect.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/UserFollowingLayout.kt
  util-compose/src/main/kotlin/team/duckie/app/android/util/compose/constraints.kt
Labels: enhancement

#437 fix: 회원가입 닉네임 중복검사 이슈 해결
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/1_ProfileScreen.kt
Labels: bug

#442 fix: 온보딩 태그가 가려지는 현상 해결
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/AdditionalInfoScreen.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/CreateProblemScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt
Labels: bug

#445 fix: Kakao Login Crash
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/1_ProfileScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
Labels: bug

#448 ExamResultScreen 제거된 State 참조하는 현상 해결
  feature-ui-exam-result/src/main/java/team/duckie/app/android/feature/ui/exam/result/screen/QuizResultScreen.kt
Labels: bug
