Repository duckie-team/duckie-android, pull requests merged in 2023-03, with the labels that each got.

#279 Feature/검색-화면-기능-구현
  data/src/main/kotlin/team/duckie/app/android/data/exam/repository/ExamRepositoryImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/recommendation/repository/RecommendationRepositoryImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/search/paging/SearchExamPagingSource.kt
  data/src/main/kotlin/team/duckie/app/android/data/search/paging/SearchTagPagingSource.kt
  data/src/main/kotlin/team/duckie/app/android/data/search/paging/SearchUserPagingSource.kt
  data/src/main/kotlin/team/duckie/app/android/data/search/repository/SearchRepositoryImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/tag/mapper/mapper.kt
  data/src/main/kotlin/team/duckie/app/android/data/tag/model/PopularTagsData.kt
  data/src/main/kotlin/team/duckie/app/android/data/tag/repository/TagRepositoryImpl.kt
  di/src/main/kotlin/team/duckie/app/android/di/usecase/search/SearchUseCaseModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/usecase/tag/TagUseCaseModule.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/exam/repository/ExamRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/exam/usecase/GetRecentExamUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/model/SearchType.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/repository/RecommendationRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/usecase/FetchSearchResultForExamUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/usecase/FetchSearchResultForUserUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/search/repository/SearchRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/search/usecase/ClearAllRecentSearchUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/search/usecase/ClearRecentSearchUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/search/usecase/GetRecentSearchUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/search/usecase/SearchExamsUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/search/usecase/SearchTagsUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/search/usecase/SearchUsersUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/tag/repository/TagRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/tag/usecase/FetchPopularTagsUseCase.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/navigator/impl/DetailNavigatorImpl.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/navigator/module/DetailNavigatorModule.kt
  feature-ui-home/build.gradle.kts
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/component/DuckTestBottomNavigation.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeActivity.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeFollowingScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/search/SearchMainScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/HomeViewModel.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/sideeffect/HomeSideEffect.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/state/HomeState.kt
  feature-ui-home/src/main/res/values/strings.xml
  feature-ui-search/build.gradle.kts
  feature-ui-search/src/main/AndroidManifest.xml
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/constants/SearchResultStep.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/constants/SearchStep.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchActivity.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchResultActivity.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchResultScreen.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchScreen.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/SearchResultViewModel.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/SearchViewModel.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/sideeffect/SearchSideEffect.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/state/SearchResultState.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/state/SearchState.kt
  feature-ui-search/src/main/res/drawable/ic_search.xml
  feature-ui-search/src/main/res/values/strings.xml
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/DuckExamCoverItem.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/UserFollowingLayout.kt
  util-exception-handling/src/main/kotlin/team/duckie/app/android/util/exception/handling/const/ErrorCode.kt
  util-ui/src/main/kotlin/team/duckie/app/android/util/ui/intent.kt
Labels: enhancement

#301 Feat/홈 화면 개밥먹기 1차 작업
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/component/DuckTestBottomNavigation.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
  feature-ui-home/src/main/res/values/strings.xml
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/UserFollowingLayout.kt
Labels: bug

#317 resolve #316
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchResultScreen.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/SearchViewModel.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/state/SearchState.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/UserFollowingLayout.kt
Labels: bug

#327 resolve #325
  data/src/main/kotlin/team/duckie/app/android/data/recommendation/repository/RecommendationRepositoryImpl.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/repository/RecommendationRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/usecase/FetchJumbotronsUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/usecase/FetchRecommendationsUseCase.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeActivity.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendFollowingExamScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendFollowingScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/search/SearchMainScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/HomeViewModel.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/dummy/SkeletonData.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/mapper/mapper.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/state/HomeState.kt
Labels: bug

#319 resolve #285
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/0_LoginScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/1_ProfileScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/state/OnboardState.kt
  feature-ui-onboard/src/main/res/values/strings.xml
Labels: bug

#331 resolves #326
  data/src/main/kotlin/team/duckie/app/android/data/kakao/repository/KakaoRepositoryImpl.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/kakao/repository/KakaoRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/kakao/usecase/GetKakaoAccessTokenUseCase.kt
  util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/exception/constant.kt
Labels: bug

#336 resolves #332 #337
  build-logic/build.gradle.kts
  build-logic/local-enums/src/main/kotlin/ConventionEnum.kt
  build-logic/src/main/kotlin/AndroidRoomConventionPlugin.kt
  data/build.gradle.kts
  data/schemas/team.duckie.app.android.data._local.DuckieDatabase/2.json
  data/src/main/kotlin/team/duckie/app/android/data/_local/Database.kt
  data/src/main/kotlin/team/duckie/app/android/data/exam/paging/ExamMeFollowingPagingSource.kt
  data/src/main/kotlin/team/duckie/app/android/data/exam/repository/ExamRepositoryImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/recommendation/paging/RecommendationPagingSource.kt
  data/src/main/kotlin/team/duckie/app/android/data/recommendation/repository/RecommendationRepositoryImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/search/repository/SearchRepositoryImpl.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/exam/repository/ExamRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/recommendation/usecase/FetchExamMeFollowingUseCase.kt
  feature-ui-exam-result/src/main/java/team/duckie/app/android/feature/ui/exam/result/screen/ExamResultScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeActivity.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendFollowingExamScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendFollowingScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeRecommendScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/ExamSection.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/ExamineeSection.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/RankingScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/HomeViewModel.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/dummy/SkeletonData.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/state/HomeState.kt
  feature-ui-notification/src/main/kotlin/team/duckie/app/android/feature/ui/notification/screen/NoticationScreen.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchResultScreen.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/SearchViewModel.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/SolveProblemActivity.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/SolveProblemScreen.kt
  gradle/libs.versions.toml
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/QuackMaxWidthDivider.kt
  util-compose/src/main/kotlin/team/duckie/app/android/util/compose/CollectAndHandleState.kt
  util-exception-handling/src/main/kotlin/team/duckie/app/android/util/exception/handling/const/ErrorCode.kt
  util-kotlin/src/main/kotlin/team/duckie/app/android/util/kotlin/exception/constant.kt
Labels: bug, dependencies

#350 Resolve #349
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/AdditionalInfoScreen.kt
  feature-ui-create-problem/src/main/kotlin/team/duckie/app/android/feature/ui/create/problem/screen/CreateProblemScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/3_TagScreen.kt
  gradle/libs.versions.toml
Labels: bug

#342 Feat/설정 페이지 구현
  app/build.gradle.kts
  data/src/main/kotlin/team/duckie/app/android/data/me/repository/MeRepositoryImpl.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/auth/usecase/ClearTokenUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/me/MeRepository.kt
  feature-ui-home/build.gradle.kts
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/HomeActivity.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/MyPageScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/HomeViewModel.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/sideeffect/HomeSideEffect.kt
  feature-ui-setting/build.gradle.kts
  feature-ui-setting/src/main/AndroidManifest.xml
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/component/SettingContentLayout.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/constans/SettingNotificationType.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/constans/SettingType.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/screen/SettingAccountInfoScreen.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/screen/SettingActivity.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/screen/SettingInquiryScreen.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/screen/SettingMainPolicyScreen.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/screen/SettingMainScreen.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/screen/SettingNotificationScreen.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/screen/SettingPrivacyPolicy.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/screen/SettingTermsOfServiceScreen.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/screen/SettingWithdrawScreen.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/viewmodel/SettingViewModel.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/viewmodel/sideeffect/SettingSideEffect.kt
  feature-ui-setting/src/main/kotlin/team/duckie/app/android/feature/ui/setting/viewmodel/state/SettingState.kt
  feature-ui-setting/src/main/res/drawable/ic_setting_kakao.xml
  feature-ui-setting/src/main/res/values/strings.xml
  feature-ui-setting/src/main/res/values/themes.xml
  gradle/libs.versions.toml
  navigator/src/main/kotlin/team/duckie/app/android/navigator/feature/intro/IntroNavigator.kt
  presentation/src/main/kotlin/team/duckie/app/android/presentation/navigator/impl/IntroNavigatorImpl.kt
  presentation/src/main/kotlin/team/duckie/app/android/presentation/navigator/module/IntroNavigatorModule.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/Dialog.kt
Labels: enhancement
