Repository duckie-team/duckie-android, pull requests merged in 2023-05, with the labels that each got.

#463 fix: 검색 탭 잘못된 padding 수정
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/search/SearchMainScreen.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/screen/SearchActivity.kt
  feature-ui-search/src/main/kotlin/team/duckie/app/android/feature/ui/search/viewmodel/SearchViewModel.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/quack/QuackNoUnderlineTextField.kt
  shared-ui-compose/src/main/res/drawable/ic_textfield_delete_16.xml
Labels: bug

#468 fix: 친구 화면에서 닉네임이 잘못 출력되는 현상
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/FriendsActivity.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/FriendsScreen.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/FriendsViewModel.kt
  feature-ui-friends/src/main/java/team/duckie/app/android/feature/ui/friends/viewmodel/state/FriendsState.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainActivity.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/MypageScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/MainSideEffect.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/viewmodel/MainViewModel.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/ProfileActivity.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/MyProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/ProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/ProfileViewModel.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/sideeffect/ProfileSideEffect.kt
  util-ui/src/main/kotlin/team/duckie/app/android/util/ui/const/Extras.kt
Labels: bug

#467 fix: 회원가입 닉네임 Writing
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/screen/1_ProfileScreen.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/OnboardViewModel.kt
  feature-ui-onboard/src/main/kotlin/team/duckie/app/android/feature/ui/onboard/viewmodel/state/OnboardState.kt
  feature-ui-onboard/src/main/res/values/strings.xml
Labels: bug

#472 시험 상세 화면 Thumbnail 모서리 둥그렇게 변경 필요
  feature-ui-detail/build.gradle.kts
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
  util-compose/src/main/kotlin/team/duckie/app/android/util/compose/constants.kt
Labels: enhancement

#471 challenge(quiz) API 구현
  data/src/main/kotlin/team/duckie/app/android/data/quiz/datasource/QuizDataSource.kt
  data/src/main/kotlin/team/duckie/app/android/data/quiz/datasource/QuizRemoteDataSourceImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/quiz/mapper/mapper.kt
  data/src/main/kotlin/team/duckie/app/android/data/quiz/model/GetQuizResponse.kt
  data/src/main/kotlin/team/duckie/app/android/data/quiz/model/PatchQuizBody.kt
  data/src/main/kotlin/team/duckie/app/android/data/quiz/model/PostQuizResponse.kt
  data/src/main/kotlin/team/duckie/app/android/data/quiz/repository/QuizRepositoryImpl.kt
  di/src/main/kotlin/team/duckie/app/android/di/datasource/BindsModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/repository/BindsModule.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/quiz/model/Quiz.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/quiz/model/QuizResult.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/quiz/repository/QuizRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/quiz/usecase/GetQuizUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/quiz/usecase/MakeQuizUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/quiz/usecase/UpdateQuizUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/search/usecase/GetSearchUseCase.kt
Labels: enhancement

#475 시험상세 페이지 챌린지(퀴즈)와 덕력고사 분기 처리
  data/src/main/kotlin/team/duckie/app/android/data/exam/mapper/mapper.kt
  data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamData.kt
  data/src/main/kotlin/team/duckie/app/android/data/exam/model/QuizInfoResponse.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/Exam.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/quiz/model/QuizInfo.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/common/BottomContent.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/common/DetailContent.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/common/TopCustomBar.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/MeasurePolicy.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/exam/ExamDetailScreen.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/quiz/QuizDetailScreen.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/viewmodel/state/DetailState.kt
  feature-ui-detail/src/main/res/values/strings.xml
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/DuckieIcon.kt
  shared-ui-compose/src/main/res/drawable/ic_crown_12.xml
Labels: enhancement

#478 덕퀴즈 시작 화면 구현
  feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/screen/StartExamScreen.kt
  feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/screen/exam/StartExamInputScreen.kt
  feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/screen/quiz/StartQuizInputScreen.kt
  feature-ui-start-exam/src/main/java/team/duckie/app/android/feature/ui/start/exam/viewmodel/StartExamState.kt
  feature-ui-start-exam/src/main/res/values/strings.xml
Labels: enhancement

#485 feat: 문제 풀기 주관식 문제 keyboard show, focus 처리
  domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/problem.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/SolveProblemActivity.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/answer/AnswerSection.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/answer/shortanswer/ShortAnswerForm.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/QuizScreen.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/SolveProblemScreen.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/viewmodel/SolveProblemViewModel.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/viewmodel/state/SolveProblemState.kt
  util-compose/src/main/kotlin/team/duckie/app/android/util/compose/PagerState.kt
Labels: enhancement

#483 feat: 마이페이지, 프로필 스켈레톤 UI 처리
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/MypageScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/ProfileActivity.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/MyProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/OtherProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/ProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/section/ExamSection.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/section/FavoriteSection.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/section/ProfileSection.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/ProfileViewModel.kt
Labels: bug, enhancement

#484 fix: 태그 추가 화면 상단탭 페딩값 수정
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/screen/SearchTagScreen.kt
Labels: bug

#482 스플래쉬에서 진입 안 될 시 에러 핸들링 처리
  data/src/test/kotlin/team/duckie/app/android/data/dummy/ExamDummyResponse.kt
  presentation/src/main/kotlin/team/duckie/app/android/presentation/IntroActivity.kt
  presentation/src/main/kotlin/team/duckie/app/android/presentation/screen/IntroScreen.kt
  presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/IntroViewModel.kt
  presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/sideeffect/IntroSideEffect.kt
  presentation/src/main/kotlin/team/duckie/app/android/presentation/viewmodel/state/IntroState.kt
  presentation/src/main/res/values/strings.xml
Labels: enhancement

#487 Profile에서 출제한 덕력고사가 나오지 않는 버그 수정
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/MyProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/OtherProfileScreen.kt
Labels: enhancement

#490 fix: QuizScreen FocusRequester not Install
  domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/problem.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/QuizScreen.kt
  feature-ui-solve-problem/src/main/kotlin/team/duckie/app/android/feature/ui/solve/problem/screen/SolveProblemScreen.kt
  util-compose/src/main/kotlin/team/duckie/app/android/util/compose/PagerState.kt
Labels: bug

#489 가이드 화면 건너뛰기가 매 페이지마다 같이 바뀌는 문제 해결
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/guide/HomeGuideFeatureScrren.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/guide/HomeGuideScreen.kt
Labels: enhancement

#491 feat: 명예의 전당 신고하기 기능 구현
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/MainScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/ExamSection.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/RankingScreen.kt
Labels: enhancement

#492 갤러리에서 전체보기 말고 다른 정렬 기준이 있는 것으로 착각하게 되는 현상 해결
  feature-photopicker/src/main/kotlin/team/duckie/app/android/feature/photopicker/PhotoPicker.kt
Labels: enhancement

#493 feat: figma 스펙에 맞게 패딩 값 수정
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/MyProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/ProfileScreen.kt
Labels: enhancement

#494 다른 유저 프로필에서 패딩이 이상한 문제 해결
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/mypage/MypageScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/ProfileActivity.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/MyProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/OtherProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/ProfileScreen.kt
Labels: enhancement

#495 feat: 유저 차단하기 기능 구현
  data/src/main/kotlin/team/duckie/app/android/data/ignore/datasource/IgnoreRemoteDataSource.kt
  data/src/main/kotlin/team/duckie/app/android/data/ignore/datasource/IgnoreRemoteDataSourceImpl.kt
  data/src/main/kotlin/team/duckie/app/android/data/ignore/repository/IgnoreRepositoryImpl.kt
  di/src/main/kotlin/team/duckie/app/android/di/datasource/BindsModule.kt
  di/src/main/kotlin/team/duckie/app/android/di/repository/BindsModule.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/ignore/repository/IgnoreRepository.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/ignore/usecase/CancelUserIgnoreUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/ignore/usecase/UserIgnoreUseCase.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/user/model/UserProfile.kt
  feature-ui-detail/src/main/kotlin/team/duckie/app/android/feature/ui/detail/screen/DetailScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/home/HomeScreen.kt
  feature-ui-home/src/main/kotlin/team/duckie/app/android/feature/ui/home/screen/ranking/RankingScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/screen/OtherProfileScreen.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/ProfileViewModel.kt
  feature-ui-profile/src/main/kotlin/team/duckie/app/android/feature/ui/profile/viewmodel/state/ProfileState.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/BackPressedHeadLineTopAppBar.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/Spacer.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/dialog/DuckieSelectableBottomSheetDialog.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/dialog/IgnoreCheckDialog.kt
  shared-ui-compose/src/main/kotlin/team/duckie/app/android/shared/ui/compose/dialog/SelectableItemBottomSheetDialog.kt
  shared-ui-compose/src/main/res/drawable/ic_flag_24.xml
  shared-ui-compose/src/main/res/values/strings.xml
Labels: enhancement

#454 logging 방식 변경
  app/build.gradle.kts
  app/src/main/kotlin/team/duckie/app/android/App.kt
  data/build.gradle.kts
  data/src/main/kotlin/team/duckie/app/android/data/_datasource/AuthorizationHeaderClient.kt
  data/src/main/kotlin/team/duckie/app/android/data/file/repository/FileRepositoryImpl.kt
  data/src/test/kotlin/team/duckie/app/android/data/CategoryRepositoryTest.kt
  data/src/test/kotlin/team/duckie/app/android/data/ExamRepositoryTest.kt
  data/src/test/kotlin/team/duckie/app/android/data/SearchRepositoryTest.kt
  gradle/libs.versions.toml
  plugin-ktor-client/build.gradle.kts
  plugin-ktor-client/src/test/kotlin/team/duckie/app/ktor/client/plugin/util/LoggingHeadersPlugin.kt
Labels: enhancement

#500 refactor: feature-setting migrate quack-v2
  common/compose/build.gradle.kts
  common/compose/src/main/kotlin/team/duckie/app/android/common/compose/typography.kt
  common/compose/src/main/kotlin/team/duckie/app/android/common/compose/ui/QuackMaxWidthDivider.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/component/SettingContentLayout.kt
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/constans/SettingDesignToken.kt
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/screen/SettingAccountInfoScreen.kt
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/screen/SettingActivity.kt
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/screen/SettingInquiryScreen.kt
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/screen/SettingMainPolicyScreen.kt
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/screen/SettingNotificationScreen.kt
  gradle/libs.versions.toml
Labels: enhancement

#502 feat: 차단에 성공했을 경우 activity finish 처리
  feature/profile/src/main/kotlin/team/duckie/app/android/feature/profile/viewmodel/ProfileViewModel.kt
Labels: enhancement

#504 fix: 덕력고사 시작 전 타이틀 텍스트 변경
  feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/screen/exam/StartExamInputScreen.kt
  feature/start-exam/src/main/res/values/strings.xml
Labels: bug

#503 fix: 덕력고사에서 focusRequster가 초기화 되지 않는 오류
  feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/SolveProblemActivity.kt
  feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/answer/AnswerSection.kt
  feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/answer/shortanswer/ShortAnswerForm.kt
  feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/screen/QuizScreen.kt
  feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/screen/SolveProblemScreen.kt
  feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/viewmodel/SolveProblemViewModel.kt
Labels: bug

#501 feat: 회원탈퇴 UI 구현
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/constans/Withdraweason.kt
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/screen/SettingActivity.kt
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/screen/SettingMainScreen.kt
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/screen/SettingWithdrawScreen.kt
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/viewmodel/SettingViewModel.kt
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/viewmodel/sideeffect/SettingSideEffect.kt
  feature/setting/src/main/kotlin/team/duckie/app/android/feature/setting/viewmodel/state/SettingState.kt
  feature/setting/src/main/res/drawable/ic_sign_out_character.xml
  feature/setting/src/main/res/values/strings.xml
Labels: enhancement

#506 feat: 주관식 문제 풀기 키보드 상태에 따른 유동적인 UI 적용
  common/compose/src/main/kotlin/team/duckie/app/android/common/compose/DuckieFitImage.kt
  common/compose/src/main/kotlin/team/duckie/app/android/common/compose/Keyboard.kt
  common/compose/src/main/kotlin/team/duckie/app/android/common/compose/size.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/problem.kt
  feature/solve-problem/build.gradle.kts
  feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/common/FlexibleSubjectiveQuestionSection.kt
  feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/question/QuestionSection.kt
  feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/screen/QuizScreen.kt
  feature/solve-problem/src/main/kotlin/team/duckie/app/android/feature/solve/problem/screen/SolveProblemScreen.kt
Labels: enhancement

#507 덕퀴즈 결과 화면 피그마 스펙에 맞게 수정
  data/src/main/kotlin/team/duckie/app/android/data/quiz/mapper/mapper.kt
  data/src/main/kotlin/team/duckie/app/android/data/quiz/model/GetQuizResponse.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/quiz/model/QuizResult.kt
  feature/exam-result/build.gradle.kts
  feature/exam-result/src/main/java/team/duckie/app/android/feature/exam/result/common/ResultBottomBar.kt
  feature/exam-result/src/main/java/team/duckie/app/android/feature/exam/result/screen/ExamResultScreen.kt
  feature/exam-result/src/main/java/team/duckie/app/android/feature/exam/result/screen/quiz/QuizResultContent.kt
  feature/exam-result/src/main/java/team/duckie/app/android/feature/exam/result/viewmodel/ExamResultState.kt
  feature/exam-result/src/main/java/team/duckie/app/android/feature/exam/result/viewmodel/ExamResultViewModel.kt
  feature/exam-result/src/main/res/values/strings.xml
Labels: enhancement

#508 덕퀴즈 시작 화면에서 문제 당 주어지는 시간, 도전 조건이 피그마 스펙에 맞게 보여져야 함
  common/android/src/main/kotlin/team/duckie/app/android/common/android/ui/const/Extras.kt
  data/src/main/kotlin/team/duckie/app/android/data/exam/mapper/mapper.kt
  data/src/main/kotlin/team/duckie/app/android/data/exam/model/ExamData.kt
  domain/src/main/kotlin/team/duckie/app/android/domain/exam/model/Exam.kt
  feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/DetailActivity.kt
  feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/viewmodel/DetailViewModel.kt
  feature/detail/src/main/kotlin/team/duckie/app/android/feature/detail/viewmodel/sideeffect/DetailSideEffect.kt
  feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/screen/quiz/StartQuizInputScreen.kt
  feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/viewmodel/StartExamState.kt
  feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/viewmodel/StartExamViewModel.kt
Labels: enhancement

#509 quiz랑 exam 로직이 같이 적용되는 부분 수정
  feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/screen/quiz/StartQuizInputScreen.kt
  feature/start-exam/src/main/java/team/duckie/app/android/feature/start/exam/viewmodel/StartExamViewModel.kt
Labels: enhancement
